= Exploring Our Infrastructure and Design

In this laboratory we will interact with two elements:

== Single Node OpenShift

This is a single-node deployment of OpenShift that will serve as the primary platform for developing, training and serving our AI models in an automated maner thanks to Red Hat OpenShift AI. Also we will run our Battery Monitoring System application here.

In order to save some time, the following operators and components have been already pre-deployed:

* **MinIO object storage**: Red Hat OpenShift AI requires an s3-compatible object storage to accommodate data and models. Also, this s3 storage is used to store artifacts generated when using pipelines. Therefore, two buckets have been created:
    ** **s3-storage**: used to store data and the new trained AI models.
    ** **pipelines**: used to store pipelines artifacts.

== RHEL Machine

A Red Hat Enterprise Linux (RHEL) machine will be used to recreate the EV charging station. This machine comes with MicroShift installed and already running. We will need MicroShift to be able to run our containerized application. This app interacts with the Battery Monitoring System to optimize the charging cicle.

== Lab design architecture

Sometimes, a picture is worth a thousand words. Below, you will find a diagram illustrating the main components involved in our solution.

*IMAGE_HERE*

