= Setting the Stage: Exploring Our Infrastructure and Design

In this laboratory we will interact with two elements:

== Single Node OpenShift

This is a single-node deployment of OpenShift that will serve as the primary platform for developing, training and serving our AI models in an automated maner thanks to Red Hat OpenShift AI. Also we will run our Battery Monitoring System application here.

In order to save some time, the following operators and components have been already pre-deployed:

* MinIO object storage deployment: Used to store data and our AI models after training.

== RHEL Machine

A Red Hat Enterprise Linux (RHEL) machine will be used to recreate the EV charging station. This machine comes with MicroShift installed and already running. We will need MicroShift to be able to run our containerized application. This app interacts with the Battery Monitoring System to optimize the charging cicle.

== Lab design architecture

It could be a bit complicated to compose and understand the scenario right now, but don't worry, below you can find a diagram that shows all the pieces involved in this lab, and we will review every single component through the different sections.

[IMAGE_HERE]

